### ISSUE TITLE
Bug - Livery GUI Dialog sometimes works, sometimes not

### ISSUE THREAD

**Issue by SP-NTX** [Octal450/MD-11#20]
GUI window with Livery sometimes works, but sometimes does not display

**To Reproduce**
1.Turn on Flightgear
2.Select MD-11
3. Click Fly!
4. MD-11/AircraftConfig/SelectLivery
5. See bug

**System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version: 2020.4.0 but in 2020.3.6 i also have this bug

**Comment by Octal450** [comment]
I just tried 20 times in a row, works fine on every variant (tested 5 per variant)
Please make reproduceable scenerio.

Kind Regards,
Josh
