### ISSUE TITLE
Bug - I got a problem woth the Auto throttle is not working at all it say someting a ATS system off idk what is going on

### ISSUE THREAD

**Issue by Haliupied33** [Octal450/MD-11#24]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 

**Additional context**

**Comment by Haliupied33** [comment]
Thanks

**Comment by Octal450** [comment]
@Haliupied33 you need to fill out the issue template, I have absolutely no idea what's going on. I will re-open the issue if you can do that. Screenshot would also help. Autothrottle works perfectly fine and as designed for me.

Kind Regards,
Josh
