### ISSUE TITLE
Bug - engine center spirals disappearing after some time of the spawn

### ISSUE THREAD

**Issue by ijkannan** [Octal450/MD-11#26]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ' select any engine variant'
2. Click on 'fly on the launcher'
3. change view to  'chase /helicopter'
4. See look at the engine spirals at center that doesn t appear 

**Expected behaviour**
i wanted engine spiral which adds a alot of pleasure in my heart while flying this plane.
 the spiral is found on the files of the MD-11 addon but it doesn t appear in game 
**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 2020.13.13

**Additional context**

**Comment by Octal450** [comment]
![image](https://user-images.githubusercontent.com/25598604/162228685-507d5958-71dc-40b9-9f07-4cc1669c3789.png)

Can't reproduce, need more steps please.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Fixed. Issue occured when livery changed.

Kind Regards,
Josh
