### ISSUE TITLE
Wrong GE milthrust

### ISSUE THREAD

**Issue by Gijsrooy** [Octal450/MD-11#28]
Hi Josh,

according to [the type certificate](https://www.easa.europa.eu/downloads/136365/en), the CF6-80C2D1F is rated at  60,690 lbf of _maximum takeoff_ trust instead of 60,960 lbf. It seems like you may have had two digits (96 instead of 69) mixed up in there, probably introduced when dropping the 1 from the _maximum ideal_ thrust of 61,960 lbf in 0fc99e08499857ca3131809037a7497582731517 😉

https://github.com/Octal450/MD-11/blob/0dc4a947a00a742df8ca0412092cb911a4d538a8/Engines/cf6-80c2d1f_1.xml#L7
https://github.com/Octal450/MD-11/blob/0dc4a947a00a742df8ca0412092cb911a4d538a8/Engines/cf6-80c2d1f_2.xml#L7
https://github.com/Octal450/MD-11/blob/0dc4a947a00a742df8ca0412092cb911a4d538a8/Engines/cf6-80c2d1f_3.xml#L7

**Comment by Octal450** [comment]
Shoot - probably my slight dyslexia at fault here. Nice catch, thank you. 

For reference, also needs fixing in the engine control file:

https://github.com/Octal450/MD-11/blob/0dc4a947a00a742df8ca0412092cb911a4d538a8/Systems/md-11-ge-engine-fadec.xml#L10

Kind Regards,
Josh
