### ISSUE TITLE
ID Autoflight MD11

### ISSUE THREAD

**Issue by SalahSabbagh** [Octal450/MD-11#33]
When iwas flying the MD11 With Thai Airways, I pressed F11 And it popups the APFS Panel And the Autopliot setting is not Available For The Plane, Could You Add This Option ID Autoflight For the md11

**Comment by SP-NTX** [comment]
This option is added under 2D Panels menu iirc in the F10 (top of the screen) menu.
<fun fact: when i saw that issue, it was so stupid so i woke up from my bed just to write this>

**Comment by Octal450** [comment]
I am assuming you mean IT-Autoflight.

No, this airplane uses a very customized version of ITAF. You need to use the AFS control panel.

Kind Regards,
Josh

**Comment by SalahSabbagh** [comment]
How do i roll the circle in the AFS Panel
