### ISSUE TITLE
autopilot disconnect

### ISSUE THREAD

**Issue by Bongoduk** [Octal450/MD-11#36]
For whatever reason whenever I try to disconnect the autopilot the alarm sounds. Which is normal. The issue here is that I can't stop the alarm and it was driving me nuts. Can you please fix this or just tell me what im doing wrong.

**Comment by Octal450** [comment]
Hi,
Like the real plane, the yoke button (shift+d) needs to be pushed again to cancel the alarm. Same with auto throttle flashing red. 

First press disengages and the second press cancels the alarm. 

Kind Regards,
Josh
