### ISSUE TITLE
Feature Request - auto pilot disconnect

### ISSUE THREAD

**Issue by Bongoduk** [Octal450/MD-11#37]
There is a problem with the MD-11. whenever the auto pilot disconnects an alarm sounds which is normal. my issue is no matter what I do the autopilot disconnect alarm can't be terminated. its super annoying and maybe there is something I'm doing wrong. I clicked the auto flight button a second time after I disconnected it and it still won't go away. can you please fix this issue?

**Comment by SP-NTX** [comment]
First this isn't an feature request. Also that's normal, look at the FCOM or something.

**Comment by Octal450** [comment]
Not autoflight button, you need to press the disconnect button a second time on the YOKE. (SHIFT+D).

Btw - I will be making a autoflight guide document soon to answer any other questions you might have.

Kind Regards,
Josh

**Comment by Bongoduk** [comment]
ok thank you very much!

**Comment by Octal450** [comment]
My pleasure
Josh
