### ISSUE TITLE
Feature Request - Remote MCDU

### ISSUE THREAD

**Issue by CyberWordPL** [Octal450/MD-11#39]
I'm always frustrated when i need to use FG Menu, or change my view to use a MCDU when using Phone is more convenient.

A good way to add Remote MCDU, is a Web panel, like a one in A320 for flightgear

**Comment by CyberWordPL** [comment]
I will do it myself

**Comment by Octal450** [comment]
OK, please submit a pull request for review when ready.

Kind Regards,
Josh

**Comment by CyberWordPL** [comment]
When WebPanelMCDU branch will be merged with master

**Comment by Octal450** [comment]
Sorry for the delay. I've been wanting to make a native looking one.

I'll get on this.

Kind Regards,
Josh
