### ISSUE TITLE
After Power Off Navigation lights and Beacon remain active

### ISSUE THREAD

**Issue by tluellma** [Octal450/MD-11#4]
Another small one.

Steps to reproduce the behaviour:
1. Make a nice flight around the world
2. Park the aircraft at a nice location, preferably at night time for better visibility
3. Stop all engines
4. Switch off Master Battery 

5. Go around the vehicle and wonder why all these lights are still active without any power.

 - OS: Windows 10
 - FlightGear version: 2020.1.1

**Comment by Octal450** [comment]
Got it, thanks! Also need to make the lights more visible!

All exterior lighting is affected including landing/taxi lights.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Fixed. Sorry for delays...

Kind Regards,
Josh

**Comment by owenexplorerph** [comment]
Thanks! and congratulations. Keep up the good work Godspeed.
Owen Explorer
@owenexplorerph

**Comment by Octal450** [comment]
Thanks!
Josh
