### ISSUE TITLE
Gear warning horn silence not working

### ISSUE THREAD

**Issue by Belegestel** [Octal450/MD-11#41]
**To Reproduce:**
- Take off
- Set flaps to full
- Retract gear
- When "Landing gear" warning is heard, press the "Landing gear horn silent" button next to throttle quadrant.

**Expected behaviour:** 
"Landing gear" warning sound stops

**System:**
    OS: Win10
    FlightGear version: 2020.3.19

**Comment by Octal450** [comment]
This is correct as per the FCOM:
"The gear warning horn will also sound any time any gear is not down and locked and the flaps are extended 31.5 degrees or more. In this case, the horn cannot be silenced with the GEAR HORN OFF button."

When the horn sounds for any other reason, it can be silenced.

Kind Regards,
Josh
