### ISSUE TITLE
Load Panel State "Ready for Taxi/Takeoff" does not activate PFD

### ISSUE THREAD

**Issue by tluellma** [Octal450/MD-11#5]
Steps to reproduce the behaviour:
1. Activate Panel State "Cold and dark" if not done
2. Now activate "Ready for Taxi"
3. Use Captains View
4. Don't see any PFD activity

5. Repeat 1-4 but with "Ready for Takeoff" instead of step 2.

**Expected behaviour**

Aircraft should be ready for Taxi / Takeoff. 

** System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version: 2020.1.1

**Comment by Octal450** [comment]
Cannot Reproduce. Can you please upload fgfs.log after doing this?

![image](https://user-images.githubusercontent.com/25598604/84574138-9c658f80-ad72-11ea-95ca-c12d718fb04b.png)

Kind Regards,
Josh

**Comment by tluellma** [comment]
I tried to reproduce but today it worked fine. :-). I close this one.

**Comment by Octal450** [comment]
Oke!
Josh
