### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by willief** [Octal450/MD-11#6]
**Describe the bug**
Cockpit does not appear

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FG 2020.2.0 on Ubuntu 20.04
2. Select MD11
3. Click "Fly"
4. FGFS opens but the pilot view does not show the cockpit      /

**Expected behaviour**
Expected to see a cockpit as in the thumbnail
**Screenshots**
![image](https://user-images.githubusercontent.com/293741/84576674-81b10c00-adae-11ea-811b-8fc99cbe246c.png)

** System (please complete the following information):**
 - OS: Ubuntu 20.04
 - FlightGear version:2020.2.0

**Additional context**

**Comment by legoboyvdlp** [comment]
Did you rename the folder, removing `-master`?

**Comment by willief** [comment]
Yes .
I deleted the folder from aircraft and reinstalled using Git. Looks OK now - Thank you for the quick reply.

**Comment by Octal450** [comment]
Glad you got it sorted!
Have good flights!

Josh
